/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OperationResearchJava;

import org.junit.Test;
import static org.junit.Assert.*;

public class OperationResearchFabricTest {
    @Test public void testAppHasAGreeting() {
        OperationResearchFabric classUnderTest = new OperationResearchFabric();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
